spring:
  datasource:
    url: jdbc:mysql://${AID_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${AID_DB_USERNAME}
    password: ${AID_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  secret: ${AID_JWT_SECRET}
  expiration: ${AID_JWT_EXPIRATION}
